export class DtoConditionOfProduct {
  productId: number = 0;
  productName: string = '';
  inQuantity: number = 0;
  outQuantity: number = 0;
  inFirstUnitPrice: number = 0;
  inFirstAmount: number = 0;
  inLastUnitPrice: number = 0;
  inLastAmount: number = 0;
  inAvaregeUnitPrice: number = 0;
  inAvarageAmount: number = 0;
  outFirstUnitPrice: number = 0;
  outFirstAmount: number = 0;
  outLastUnitPrice: number = 0;
  outLastAmount: number = 0;
  outUnitPrice: number = 0;
  outAmount: number = 0;
  balance: number = 0;
}
